application: endpoint-project-1076
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Static resources
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /bootstrap
  static_dir: static/bootstrap
- url: /fileinput
  static_dir: static/fileinput
# Endpoints handler
- url: /_ah/spi/.*
  secure: always
  script: recognize_api.APPLICATION
# Website Handlers
- url: /.*
  secure: always
  script: recognize.app

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: PIL
  version: latest