application: endpoint-project-1076
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /js
  static_dir: static/js
- url: /bootstrap
  static_dir: static/bootstrap
- url: /
  static_files: templates/index.html
  upload: templates/index\.html
- url: /admin
  static_files: templates/admin.html
  upload: templates/admin\.html
- url: /match
  static_files: templates/match.html
  upload: templates/match\.html
- url: /correlate
  static_files: templates/correlate.html
  upload: templates/correlate\.html
- url: /oddmanout
  static_files: templates/oddmanout.html
  upload: templates/oddmanout\.html
- url: /_ah/spi/.*
  script: recognize_api.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0