application: endpoint-project-1076
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /bootstrap
  static_dir: static/bootstrap
- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always
- url: /upload
  script: recognize.app
- url: /match.*
  script: recognize.app
- url: /create
  script: recognize.app
- url: /question
  script: recognize.app
- url: /admin
  static_files: templates/admin.html
  upload: templates/admin\.html
- url: /correlate
  static_files: templates/correlate.html
  upload: templates/correlate\.html
- url: /oddmanout
  static_files: templates/oddmanout.html
  upload: templates/oddmanout\.html
- url: /_ah/spi/.*
  script: recognize_api.APPLICATION

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest